### ISSUE TITLE
have be used in production?  

### ISSUE THREAD

**Issue by notedit** [djwackey/dorsvr#6]
it just like live555 at first glance.

**Comment by djwackey** [comment]
yes, i want it like live555 as a RTSP server, now i'm reading crtmpserver's code, later i'll add rtmp feature.
By the way, i saw your company's information at boss zhipin.:)

**Comment by notedit** [comment]
:) 
i am looking for a rtsp server as a gateway to webrtc.   rtmp support will be great,  i am using  srs as rtmp server  for now.
any interest  for joining out small team?

**Comment by djwackey** [comment]
I would like to know more about your team.After that, I will update my resume and show it to you.
Now the server haven't run in production yet,Still much work need to do.etc:go channel, modular and more test.

**Comment by notedit** [comment]
if you have a cv,  here is my email  leeoxiang@gmail.com.

i will give you more info about our team.  :)
