### ISSUE TITLE
r.Sink.SSRC undefined

### ISSUE THREAD

**Issue by Himer** [djwackey/dorsvr#7]
# github.com/djwackey/dorsvr/livemedia
/root/go/src/github.com/djwackey/dorsvr/livemedia/rtcp_linux_amd64.go:97: undefined: EVENT_REPORT
/root/go/src/github.com/djwackey/dorsvr/livemedia/rtcp_linux_amd64.go:236: r.Sink.SSRC undefined (type IMediaSink has no field or method SSRC, but does have ssrc)
/root/go/src/github.com/djwackey/dorsvr/livemedia/rtcp_linux_amd64.go:386: r.Sink.SSRC undefined (type IMediaSink has no field or method SSRC, but does have ssrc)
/root/go/src/github.com/djwackey/dorsvr/livemedia/rtcp_linux_amd64.go:391: r.Sink.SSRC undefined (type IMediaSink has no field or method SSRC, but does have ssrc)
/root/go/src/github.com/djwackey/dorsvr/livemedia/rtp_interface.go:78: i.gs.TTL undefined (type *groupsock.GroupSock has no field or method TTL)
/root/go/src/github.com/djwackey/dorsvr/livemedia/rtp_interface.go:78: too many arguments in call to i.gs.Output
        have ([]byte, uint, <T>)
        want ([]byte, uint)
/root/go/src/github.com/djwackey/dorsvr/livemedia/server_media_session.go:11: undefined: MEDIA_SERVER_VERSION

**Comment by falconray0704** [comment]
I got the same issue....

**Comment by zyfdegh** [comment]
+1

```sh
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ferdi/GOPATH"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build633701637=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```
