### ISSUE TITLE
after go get

### ISSUE THREAD

**Issue by spaceblock** [djwackey/dorsvr#9]
../github.com/djwackey/dorsvr/livemedia/stream_state.go:14: undefined: RTCPInstance

**Comment by zyfdegh** [comment]
+1

```sh
$ go verison
go version go1.7.3 windows/amd64
```

```sh
$ go env
set GOARCH=amd64
set GOBIN=C:\GOPATH\bin
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\GOPATH
set GORACE=
set GOROOT=C:\GOPATH\src\github.com\golang\go
set GOTOOLDIR=C:\GOPATH\src\github.com\golang\go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1
```

**Comment by sbreencs** [comment]
+ 1 

go version go1.9 windows/amd64

set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\steve\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\steve\AppData\Local\Temp\go-build609262063=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config

**Comment by srinivasnks** [comment]
GOOS=linux should fix it. RTCPInstance is only defined in livemedia/rtcp_linux_386.go and livemedia/rtcp_linux_amd64.go
